# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "garner"
  s.version = "0.4.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Doubrovkine", "Frank Macreery"]
  s.date = "2013-07-11"
  s.description = "Garner is a cache layer for Ruby and Rack applications, supporting model and instance binding and hierarchical invalidation."
  s.email = "dblock@dblock.org"
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    "lib/garner.rb",
    "lib/garner/cache.rb",
    "lib/garner/cache/binding.rb",
    "lib/garner/cache/context.rb",
    "lib/garner/cache/identity.rb",
    "lib/garner/config.rb",
    "lib/garner/mixins/active_record.rb",
    "lib/garner/mixins/active_record/base.rb",
    "lib/garner/mixins/mongoid.rb",
    "lib/garner/mixins/mongoid/document.rb",
    "lib/garner/mixins/mongoid/identity.rb",
    "lib/garner/mixins/rack.rb",
    "lib/garner/strategies/binding/invalidation/base.rb",
    "lib/garner/strategies/binding/invalidation/binding_index.rb",
    "lib/garner/strategies/binding/invalidation/touch.rb",
    "lib/garner/strategies/binding/key/base.rb",
    "lib/garner/strategies/binding/key/binding_index.rb",
    "lib/garner/strategies/binding/key/cache_key.rb",
    "lib/garner/strategies/binding/key/safe_cache_key.rb",
    "lib/garner/strategies/context/key/base.rb",
    "lib/garner/strategies/context/key/caller.rb",
    "lib/garner/strategies/context/key/jsonp.rb",
    "lib/garner/strategies/context/key/request_get.rb",
    "lib/garner/strategies/context/key/request_path.rb",
    "lib/garner/strategies/context/key/request_post.rb",
    "lib/garner/version.rb"
  ]
  s.homepage = "http://github.com/artsy/garner"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "Garner is a cache layer for Ruby and Rack applications, supporting model and instance binding and hierarchical invalidation."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rack>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<multi_json>, [">= 1.3.0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 1.3.0"])
      s.add_development_dependency(%q<grape>, [">= 0.2.0"])
      s.add_development_dependency(%q<sinatra>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.10.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<mongoid>, [">= 3.0.0"])
      s.add_development_dependency(%q<mongoid_slug>, [">= 1.0.0"])
      s.add_development_dependency(%q<dalli>, [">= 0"])
      s.add_development_dependency(%q<activerecord>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<coveralls>, [">= 0"])
      s.add_development_dependency(%q<method_profiler>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<redcarpet>, [">= 0"])
      s.add_development_dependency(%q<github-markup>, [">= 0"])
    else
      s.add_dependency(%q<rack>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<multi_json>, [">= 1.3.0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 1.3.0"])
      s.add_dependency(%q<grape>, [">= 0.2.0"])
      s.add_dependency(%q<sinatra>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.10.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<mongoid>, [">= 3.0.0"])
      s.add_dependency(%q<mongoid_slug>, [">= 1.0.0"])
      s.add_dependency(%q<dalli>, [">= 0"])
      s.add_dependency(%q<activerecord>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<coveralls>, [">= 0"])
      s.add_dependency(%q<method_profiler>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<redcarpet>, [">= 0"])
      s.add_dependency(%q<github-markup>, [">= 0"])
    end
  else
    s.add_dependency(%q<rack>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<multi_json>, [">= 1.3.0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 1.3.0"])
    s.add_dependency(%q<grape>, [">= 0.2.0"])
    s.add_dependency(%q<sinatra>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.10.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<mongoid>, [">= 3.0.0"])
    s.add_dependency(%q<mongoid_slug>, [">= 1.0.0"])
    s.add_dependency(%q<dalli>, [">= 0"])
    s.add_dependency(%q<activerecord>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<coveralls>, [">= 0"])
    s.add_dependency(%q<method_profiler>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<redcarpet>, [">= 0"])
    s.add_dependency(%q<github-markup>, [">= 0"])
  end
end

